service: subdocument-module-array

package:
  patterns:
    - '!.git/**'
    - '!.idea/**'
    - '!.vscode/**'
    - '!.test/**'
    - '!docs/**'
    - '!node_modules/serverless-*/**'
    - '!node_modules/chai/**'
    - '!node_modules/eslint*/**'
    - '!node_modules/mocha/**'
    - '!node_modules/sinon/**'
    - '!node_modules/uuid/**'

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'prod'}
  region: us-east-1
  timeout: 10
  memorySize: 128
  versionFunctions: false

  environment:
    ENV: ${env:APP_ENV, 'local'}
    REGION: ${env:APP_REGION, 'localhost'}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
            - lambda:InvokeAsync
          Resource: "*"

custom:
  region: ${self:provider.region}
  stage: ${opt:stage, self:provider.stage}
  prefix: ${self:custom.stage}-${self:service}
  config: ${self:custom.prefix}-config

  customDomain:
    domainName: sda.projetos.lauraesteves.com
    certificateArn: ${env:ACM_CERTIFICATE_ARN}
    stage: ${self:provider.stage}
    basePath: ''
    createRoute53Record: true
    createRoute53IPv6Record: true
    endpointType: edge
    securityPolicy: tls_1_2
    autoDomain: true

  serverless-offline:
    host: '0.0.0.0'

  splitStacks:
    perFunction: true
    perType: true

plugins:
  - serverless-domain-manager
  - serverless-offline

functions: ${file(serverless-dynamic.js)}
